# Generated by Django 3.2.9 on 2021-11-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyplans', '0002_auto_20211110_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_latitude',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_longitude',
            field=models.CharField(default='', max_length=20),
        ),
    ]
