# Generated by Django 3.2.9 on 2021-11-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlyplans', '0003_auto_20211110_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location_longitude',
        ),
        migrations.CreateModel(
            name='OnlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280, verbose_name='Titill')),
                ('location_latitude', models.CharField(default='', max_length=20, verbose_name='Breiddargráða')),
                ('location_longitude', models.CharField(default='', max_length=20, verbose_name='Lengdargráða')),
                ('reach', models.FloatField(verbose_name='Umfang')),
                ('when', models.DateTimeField(verbose_name='Tímasetning')),
                ('duration', models.IntegerField(verbose_name='Hve lengi?')),
                ('friendsonly', models.BooleanField(verbose_name='Bara fyrir vini')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlyplans.profile')),
            ],
        ),
    ]
