# Generated by Django 3.2.9 on 2021-11-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyplans', '0004_auto_20211110_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlyplan',
            name='friendsonly',
            field=models.BooleanField(default=False, verbose_name='Bara fyrir vini'),
        ),
        migrations.AlterField(
            model_name='onlyplan',
            name='owner',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='onlyplan',
            name='reach',
            field=models.FloatField(default=5, verbose_name='Umfang'),
        ),
    ]
