# Generated by Django 3.2.9 on 2021-11-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyplans', '0005_auto_20211110_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlyplan',
            name='reach',
            field=models.IntegerField(verbose_name='Umfang'),
        ),
    ]
