# Generated by Django 3.2.9 on 2021-11-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyplans', '0006_alter_onlyplan_reach'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='_onlyplans_profile_friends_+', to='onlyplans.Profile'),
        ),
        migrations.DeleteModel(
            name='FriendMgmt',
        ),
    ]
